### ISSUE TITLE
address.db.gz and streets.db.gz are not accessable any more from https://s3.amazonaws.com

### ISSUE THREAD

**Issue by semeyon** [pelias/kubernetes#110] opened 2019-10-25 17:41 UTC
Hey team!

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

When I'm trying to run the interpolation engine it fails to start b/c https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/street.db.gz and https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/address.db.gz are not accessible any more.

    wget -O - https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/street.db.gz
    wget -O - https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current/address.db.gz

Both returns: Error 403: Forbidden.

Is there any alternative? B/c pretty important service stopped to work. :(

**Comment by orangejulius** [comment] 2019-10-28 13:43
Hi @semeyon,
If you could, please do not create duplicate issues for problems. It will not get you help any faster and takes up time on the part of the project maintainers.

In this case the answer is also found in the readme of this repository:

>Announcement: This project previously took advantage of full planet data for the Placeholder and Interpolation services hosted by Nextzen. Unfortunately this hosting is no longer available. By default, this project will now download data for the Portland Metro area.

Closed as duplicate of https://github.com/pelias/interpolation/issues/224

**Closed by orangejulius** 2019-10-28 13:43 UTC

**Comment by semeyon** [comment] 2019-10-28 13:51
I’m very sorry for in convince. 

One of very important services stoped to work and 
1. It was quite unclear where should I post issue.
2. To generate data for whole planet is quite hard because the interpolation README/documentation is very unclear and hard to reproduce for whom is not a part the dev team.
3. Nextzen revoke access but files are still on the s3 bucket…
